header <- read.table('household_power_consumption.txt', sep = ';', header = FALSE, nrows = 1, stringsAsFactors = FALSE)
hpc <- read.table('household_power_consumption.txt', sep = ';', header = FALSE, skip = 66637, nrows = 2880, stringsAsFactors = FALSE, col.names = header)
hpc$Datetime <- strptime(paste(hpc$Date, hpc$Time, sep = ' '), '%d/%m/%Y %H:%M:%S')
png("plot4.png", width = 480, height = 480)
par(mfrow = c(2, 2))
plot(hpc$Datetime, hpc$Global_active_power, type = 'l', xlab = '', ylab = 'Global Active Power', cex = 0.2)
plot(hpc$Datetime, hpc$Voltage, type = 'l', xlab = 'datetime', ylab = 'Voltage')
plot(hpc$Datetime, hpc$Sub_metering_1, type = 'l', ylab = 'Energy sub metering', xlab = '')
lines(hpc$Datetime, hpc$Sub_metering_2, type = 'l', col = 'red')
lines(hpc$Datetime, hpc$Sub_metering_3, type = 'l', col = 'blue')
legend('topright', c('Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3'), lty = 1, lwd = 2.5, col = c('black', 'red', 'blue'), bty = 'o', box.col = 'white')
plot(hpc$Datetime, hpc$Global_reactive_power, type = 'l', xlab = 'datetime', ylab = 'Global_reactive_power')
dev.off()
