header <- read.table('household_power_consumption.txt', sep = ';', header = FALSE, nrows = 1, stringsAsFactors = FALSE)
hpc <- read.table('household_power_consumption.txt', sep = ';', header = FALSE, skip = 66637, nrows = 2880, stringsAsFactors = FALSE, col.names = header)
hpc$Datetime <- strptime(paste(hpc$Date, hpc$Time, sep = ' '), '%d/%m/%Y %H:%M:%S')
png("plot3.png", width = 480, height = 480)
plot(hpc$Datetime, hpc$Sub_metering_1, type = 'l', ylab = 'Energy Submetering', xlab = '')
lines(hpc$Datetime, hpc$Sub_metering_2, type = 'l', col = 'red')
lines(hpc$Datetime, hpc$Sub_metering_3, type = 'l', col = 'blue')
legend('topright', c('Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3'), lty = 1, lwd = 2.5, col = c('black', 'red', 'blue'))
dev.off()
