header <- read.table('household_power_consumption.txt', sep = ';', header = FALSE, nrows = 1, stringsAsFactors = FALSE)
hpc <- read.table('household_power_consumption.txt', sep = ';', header = FALSE, skip = 66637, nrows = 2880, stringsAsFactors = FALSE, col.names = header)
png('plot1.png', width = 480, height = 480)
hist(hpc$Global_active_power, main = 'Global Active Power', xlab = 'Global Active Power (kilowatts)', col = 'red')
dev.off()
